spring.application.name=demo

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE
spring.datasource.username=matteo
spring.datasource.password=YourStronPassword01
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


# se vuoi provare (opzionale)
jakarta.persistence.jdbc.url=jdbc:oracle:thin:@localhost:1521:xe
